server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/users/**, /auth/**
            
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/profiles/**
          filters:
            - AuthenticationFilter
            
        - id: matching-service
          uri: ${MATCHING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/match/**
          filters:
            - AuthenticationFilter
            
        - id: operator-service
          uri: ${OPERATOR_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/operators/**
            - Path=/operators/properties/**
          filters:
            - AuthenticationFilter
