server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /auth/**
            
        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/profiles/**
          filters:
            - AuthenticationFilter
            
        - id: matching-service
          uri: http://localhost:8083
          predicates:
            - Path=/match/**
          filters:
            - AuthenticationFilter
            
        - id: operator-service
          uri: http://localhost:8084
          predicates:
            - Path=/operators/**
          filters:
            - AuthenticationFilter
